### ISSUE TITLE
Small inconsistency and UX issue in Elastic

### ISSUE THREAD

**Issue by alecpl** [johndoh/roundcube-contextmenu#104]
Please, consider https://git.kolab.org/T3670.

**Comment by johndoh** [comment]
> 3. When one wants to get even one level deeper (e.g. "More" > "Copy to" > "Archive"), one must click on the corresponding field so that the next (third) drop down menu opens!
> 
> This is confusing because on the other level, the drop down menu for the next level opened automatically, so the user expects this to happen here again, and doesn't even think that there might be further options in another drop down menu! The latter is made worse by the fact that - unlike in the first drop down menu - there are no arrows shown next to those options which offer further "sub-options"! So, as I said, the user can't even know that there might be further options and might thus not try to make the necessary click.

The move and copy widgets are not drop down menus. For the mark and more actions menus the code is different (how the elements are described in the DOM) it is possible to detext these as menu opening functions and, because I like it, the little arrow is added. With copy/move these are regular Roundcube commands, there is no way to tell (short of hard coding it) that executing them will cause a widget to open.

More generally I think executing commands on mouseover would make accidental execution easier. If its a consistency thing I suppose a config option could be added to enable/disable the mouseover for sub menus. I'm not sure its needed though. Its standard Roundcube behaviour that to move/copy a message you go to the more actions menu and click move/copy. So I think expecting users to know they have to click move/copy is reasonable.

> Additionally: (This is just a tiny thing concerning the aesthetics and consistency of the UI, but since we've already started criticizing it...)
> The third drop down menu opens not one simply in a new box directly next to other, but has a little triangle at the side.

Elastic has special handling for popup menus. Plugins which create their own popups, like the contextmenu, can override this but the move/copy widgets come from the core and short of writing my own version, duplicating core code, there is no way to change they styling.

**Comment by johndoh** [comment]
I’ve made a few improvements to the display of the submenus to make them more consistent with the rest of Elastic. I’ve also added a way for admins to be able to change the ‘show submenus on hover’ behaviour if they want to.

The last part about the sub menu symbols. I copy what Elastic does in the sub menus – it has no arrows for the move/copy commands. Whether or not they should be on the mark/more option in the main menu is debateable but I like them. Note: These are already hidden on small screens so that the menu created by this plugin is the same as the one in the core.
