### ISSUE TITLE
Need help with a bug

### ISSUE THREAD

**Issue by alecpl** [johndoh/roundcube-contextmenu#124]
Hi, 

I'm working on https://github.com/roundcube/roundcubemail/issues/7189 and following change breaks Move to/Copy to actions in contextmenu. I'm not sure why. I guess you disable the command for some reason. Could you check if there's some issue that could be fixed in contextmenu to make this working?

```diff
--- a/program/js/app.js
+++ b/program/js/app.js
@@ -3198,12 +3198,13 @@ function rcube_webmail()
   this.copy_messages = function(mbox, event, uids)
   {
     if (mbox && typeof mbox === 'object') {
+      if (mbox.uids) uids = mbox.uids;
       mbox = mbox.id;
     }
     else if (!mbox) {
       uids = this.env.uid ? [this.env.uid] : this.message_list.get_selection();
-      return this.folder_selector(event, function(folder) {
-        ref.copy_messages(folder, null, uids);
+      return this.folder_selector(event, function(folder, obj) {
+        ref.command('copy', {id: folder, uids: uids}, obj, event);
       });
     }
 
@@ -3225,12 +3226,13 @@ function rcube_webmail()
   this.move_messages = function(mbox, event, uids)
   {
     if (mbox && typeof mbox === 'object') {
+      if (mbox.uids) uids = mbox.uids;
       mbox = mbox.id;
     }
     else if (!mbox) {
       uids = this.env.uid ? [this.env.uid] : this.message_list.get_selection();
-      return this.folder_selector(event, function(folder) {
-        ref.move_messages(folder, null, uids);
+      return this.folder_selector(event, function(folder, obj) {
+        ref.command('move', {id: folder, uids: uids}, obj, event);
       });
     }
 
```
the change is planned for backport to 1.4.

**Comment by johndoh** [comment]
I think this is related to https://github.com/roundcube/roundcubemail/pull/6145. The contextmenu plugin enables commands when its opened and then returns them to their original state so as not to mess up the main UI.

The move and copy functions are unique in that they have a 2 stage execution and the actual command execution isn't until stage 2 which is after contextmenu is closed. The state of an command is checked before any JS events are triggered so I think the solution can only be found inside app.js

I'm not sure what is best though as its really only useful for plugins rather than anything in the core. The command could be temp enabled like it is inside contextmenu:

```diff
       uids = this.env.uid ? [this.env.uid] : this.message_list.get_selection();
-      return this.folder_selector(event, function(folder) {
-        ref.move_messages(folder, null, uids);
+      return this.folder_selector(event, function(folder, obj) {
+        var prev_command = ref.commands['move'];
+        rcmail.enable_command('move', true);
+        ref.command('move', {id: folder, uids: uids}, obj, event);
+        rcmail.enable_command('move', prev_command);
       });
```

Or may be something added to `rcmail.command()` to make it pass the enabled check.

**Comment by alecpl** [comment]
Fixed with https://github.com/roundcube/roundcubemail/commit/cb8c07843bd63f4c98. Thanks.
