### ISSUE TITLE
Duplicate Open in new window entry in folders menu

### ISSUE THREAD

**Issue by alecpl** [johndoh/roundcube-contextmenu#95]
I see two Open in new window entries in the folders menu when enabling kolab_tags plugin. I see also duplicated Expand All and Collapse All, but they are display:none.

Any hints on what can cause that? I'm using Elastic.

**Comment by johndoh** [comment]
The rcmfolder-menu div is in the source twice. Do you think its possible that the render_page hook is being executed twice?

**Comment by alecpl** [comment]
It is indeed. https://git.kolab.org/diffusion/RPK/browse/master/plugins/kolab_tags/lib/kolab_tags_engine.php;1f0f28204900364d01ba2fd8b9b99e8d44a7b3cc$71

I could probably fix this in kolab_tags, but I think it's better to do this on contextmenu side. PR created.

**Comment by johndoh** [comment]
merged thanks.

**Comment by johndoh** [comment]
In mail and addressbook, where there are currently menus, this fix is fine. But I was just looked at extending the plugin into other tasts and realised this is not always the case that the template name matches the task. For example the settings task.

I know you want to fix this on the contextmenu side but I'm starting to think that might not be possible. What about adding the $write param to the render_page hook, or only executing the hook if $write is true?

**Comment by alecpl** [comment]
Then accept only these template names you support. We can also add the hook argument you propose, though I'm not sure it would be better.

**Comment by johndoh** [comment]
I don't like the idea of relying on template names because using the example of the settings section there are several different templates: settings, folders, identities for example. If I've read the code correctly then as long as $write is true it must be the "real" execution of render_page hood - the result is output to the client. and if a plugin had that info then it could decide to do that ever it likes, regardless of the task or action.

BTW I was thinking in kolab_tags, could you not use the rcmail_output_html::just_parse() method rather than parse()? then there would be no duplicate call of the render_page hook.

**Comment by alecpl** [comment]
Just_parse() is not exactly the same, so I prefer to not change the code this way.

I added 'write' argument to the `render_page` hook in https://github.com/roundcube/roundcubemail/commit/38d275445d072445f0740c08b4230f683056076b

**Comment by johndoh** [comment]
thanks. I've updated my code. can you confirm its still ok with the kolab_tags plugin?

**Comment by alecpl** [comment]
Looks fine now. Thanks.
